language: node_js

node_js:
  - "8"

branches:
  only:
  - master
  - develop
  - feature-branch-test

script: npm run buildWebpack && npm run unitMeta && npm run unit -- --single-run

cache:
  directories:
    - node_modules

git:
  depth: 1
